dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: uB0vKHWzq+XYZJVBcdE3wWG8oIiIDx+3JxhqF69c/ENgBULkXnnyUzDJHFnGuW/mVfcTP+Ogoz61f0fQ8UtBWPDWlbLIQCiw4zJdy1I6GUQtp7+7aL006o23kOQoozLg1mMnXwxPga+lw8glLpIz2VWjkWrowMaDnFCmmAbzCODPvZFuyAiqkAIyUTxFuaggywlC1DtDenHRs9oYkaaCDzqM3XVt9NnSyOArd37TKEImxLoC7U3K88IaEt53Cc/dvs/dFtVqZG5X27Fsgxt5YzovwChm5MIFtx48qQoPLcDyzizNxTOi1VXVOnW/rOOPF1FqlsDtgRuuBy0KLnzZeHFi3MFqJHqm3Xsv8AzhSj//V3LO8pFKpmT0sRVWrZfHnFShMvrC9v8nri2oww5SZ8Shs3q+U+RfZ3fGCELCQ17w+nBZ+YGJfsRQ+yXkLSohzqsFsfuFvZ2R1XLsik3DJGnV6JqwdoUrfGAIUz2Zxr1i/oei6nn1/jIf+eXLKN6Ie3CjNEdY7PCSCM00SVcDHmJ5Eoh98VQEOBQ5FOQRdM8buYg6g6y6xqecE3u+LwZ/AT3UOYcypOaDyXwyzaqITl56XCp1fwDRSbxuHOqhwBsz3aEiuGvSgXQJND8Pk8L77NyZagLe+Ii8dN99BZnNJJwwtF59qFOu+u2cDWIugoc=
