dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: YMaJwEHLQsxDd7Ih5bdEPKVz0NCQMTRYHZWDnyEBXTYyRkVIM//KkDO/gqYLfeKKzEzVwnf5xHKFFQicPGTYax8YF1RA8HXgWVp1CtpMZqLE3L0Nuh0asTvk5UFpTHLtnKzXEwE3pHm5Uyr1KbgpYKSR2g1LV+faEtnNQEpl6H70e1tQDblzAiwoztY27zjC5AY8XlYo6Hc4J55NOaLWdMVkyaxtsDQId6GnC8Wbzmt/mwg3B/vnEmz6HmRp06jwChjgq2bhuNGjOQkpr68b08dqvuMBQ6e0ajPuOaGXSzsklCJfknN/UXD+MfCIcnPibcpjR2nm4Hkz8GmR8YQlnHQyysbn+srxJzGKXPVsXb8ynoNxWLCuFb9vl1p+oq1KKQddjygGaHkXLJOevFPZBC1VreGUR4+tqmWDrrThFYxM+NtIsEmRZxGwBJnm66n2ryRpGaOg3HezDiDJiuxBiSJn9kPJJ6RduQUi9AYq38ld+Byjdr3a4v+AtBtNZ5yK/46gxqXUCfpEQOIgHo2UN1YXKhAazKPhGHLFe7vAGvvjV4NoVOf7u51yP8E03XL6XFjrw1D1exBwKVT49COS50nZxs6sL+Tk8O58/iUKIoKDd0tIwkUaXYO/+CUXF8kW6+TbxMDctyAyr8oH++8qao8EvzAo/JBlRZIVO4pS9fc=
