---
- name: Configure MongoDB
  hosts: db
  become: true # <-- run all tasks as root
  vars:
    mongo_bind_ip: 0.0.0.0  # <-- variable for our mongod template
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
