---
- name: Deploy App
  hosts: app
  tasks:
    - name: Fetch the last version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith # <-- name of desired branch
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit # <-- where we should run 'bundle' command

  handlers:
  - name: restart puma
    become: true # <-- run task as root
    systemd: name=puma state=restarted
