plugin: gcp_compute
projects:
  - infra-262415
zones:
  - europe-west3-a
auth_kind: serviceaccount
service_account_file: ~/.config/gcloud/infra-a912ac4f7cd5.json
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
