---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true # <-- run all tasks as root
  vars:
    mongo_bind_ip: 0.0.0.0  # <-- variable for our mongod template
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true # <-- run all tasks as root
  vars:
    db_host: 10.156.0.4
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=reloaded

- name: Deploy App
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Fetch the last version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith # <-- name of desired branch
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit # <-- where we should run 'bundle' command

  handlers:
  - name: restart puma
    become: true # <-- run task as root
    systemd: name=puma state=restarted
